
name: Build Android APK (Fallback)

on:
  workflow_dispatch: # Solo ejecución manual
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'debug'
        type: choice
        options:
        - debug
        - release

jobs:
  build-android-fallback:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Free up disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        
    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '17'
        
    - name: Setup Android SDK
      run: |
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        mkdir -p $HOME/android-sdk/cmdline-tools/latest
        mv cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/
        
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
        
    - name: Accept licenses and install packages
      run: |
        yes | sdkmanager --licenses
        sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools"
        
    - name: Install npm dependencies
      run: |
        npm ci --legacy-peer-deps
        
    - name: Build web app
      run: npm run build
      
    - name: Setup Capacitor Android
      run: |
        npx cap add android || echo "Android platform may already exist"
        npx cap sync android
        
    - name: Configure Android build
      run: |
        cd android
        echo "sdk.dir=$ANDROID_HOME" > local.properties
        echo "org.gradle.java.home=$JAVA_HOME" >> gradle.properties
        echo "org.gradle.jvmargs=-Xmx2048m" >> gradle.properties
        chmod +x gradlew
        
    - name: Build APK
      run: |
        cd android
        ./gradlew clean
        ./gradlew assemble${{ github.event.inputs.build_type || 'debug' }} --info --stacktrace
        
    - name: Find and upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk-fallback
        path: |
          android/app/build/outputs/apk/**/*.apk
        retention-days: 7
